// <auto-generated />
using System;
using McbEdu.Mentorias.ShopDemo.Infrascructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McbEdu.Mentorias.ShopDemo.Infrascructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221123194318_OrderMigration")]
    partial class OrderMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Customer", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Item", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitaryValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("OrderIdentifier");

                    b.HasIndex("ProductIdentifier");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Order", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("CustomerIdentifier");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Product", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Item", b =>
                {
                    b.HasOne("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Order", b =>
                {
                    b.HasOne("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Models.DTOs.Product", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
