// <auto-generated />
using System;
using McbEdu.Mentorias.ShopDemo.Infrascructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McbEdu.Mentorias.ShopDemo.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230104150040_BaseMigration")]
    partial class BaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.CustomerContext.DTO.Customer", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Identifier");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.ItemContext.DTO.Item", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("OrderIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("ProductIdentifier")
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitaryValue")
                        .HasColumnType("DECIMAL");

                    b.HasKey("Identifier");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("OrderIdentifier");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.OrderContext.DTO.Order", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CustomerBirthdate")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("CustomerIdentifier")
                        .HasMaxLength(36)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("DATETIME");

                    b.HasKey("Identifier");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.ProductContext.DTO.Product", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Identifier");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.ItemContext.DTO.Item", b =>
                {
                    b.HasOne("McbEdu.Mentorias.ShopDemo.Domain.Contexts.OrderContext.DTO.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("McbEdu.Mentorias.ShopDemo.Domain.Contexts.OrderContext.DTO.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
